### PR TITLE
feat: Adding sops feature

### PR DESCRIPTION
**Pull request by timdeluxe**

### CODE REVIEW

**Review by dploeger — APPROVED** [review]
Looks great. Thanks! 🎁

**Comment by timdeluxe** [comment]
@ThomasMinor or @rexhinvorpsi i need two approvals, can one of you check and approve this as well please? Thanks!

**Review by rexhinvorpsi — APPROVED** [review]

**Comment by ThomasMinor** [comment]
Does the SOPS package contain the AGE package?

**Comment by timdeluxe** [comment]
@ThomasMinor 
> Does the SOPS package contain the AGE package?

SOPS containts AGE libraries to work with AGE keys. It does not include the age CLI itself, but it can work with created keys. I wouldn't include the age cli as well, as it would unnecessarily bloat the container. Key creation is kind of a one time operation and can be done outside of cloudcontrol.

Can you approve as well please, so i know it is fine with you - even despite the fact that this PR already reached the 2 necessary approvals?

**Pull request merged**
