### PR TITLE
fix: correct wrong encodings

### PR DESCRIPTION
**Pull request by ThomasMinor**
- fix encodings
- reformat file

### CODE REVIEW

**Comment by timdeluxe** [comment]
@dploeger Needs to comment here...

The README.md is generated (manually) by mkdoc.js. Your fixes would be overwritten, when the next generated README.md is pushed.
So the source documents need to get fixed (or the generator) i think...

**Comment by ThomasMinor** [comment]
> 

Meh! Stupid me!!

**Comment by ThomasMinor** [comment]
heya, @dploeger & @timdeluxe , What do you like more: The aligned Table version or the bullet list one?

**Comment by timdeluxe** [comment]
bullet list one.
layouting with tables is something from the last century 😉

**Comment by dploeger** [comment]
Also voting for bullet list. Is better for accessibility as well.

**Comment by ThomasMinor** [comment]
> bullet list one. layouting with tables is something from the last century 😉

It's more like a listing of content, but ok.

**Review by timdeluxe — APPROVED** [review]

**Review by dploeger — APPROVED** [review]

**Comment by dploeger** [comment]
@ThomasMinor I'm sorry, I think my last PR merge required you to rebase this

**Pull request merged**
