### PR TITLE
feat: Added labels to all images

### PR DESCRIPTION
**Pull request by dploeger**
as required by Artifacthub
https://artifacthub.io/docs/topics/repositories/container-images/

I wanted to add CloudControl to the image container registry at Artifacthub, but they require certain labels. Introduced mo to do the dynamic labels in the Dockerfile.suffix

### CODE REVIEW

**Comment by timdeluxe** [comment]
Mooo! 🐄
(sorry could not resist)

Does the suffix file also work without sending it through mo? This should work for local development on cloudcontrol (not replaced template placeholders shouldn't be an issue for local development). If it does not work, the suffix File should be rather a .mo file (like Dockerfile.suffix.mo), so that one is aware that the Dockerfile.suffix needs to be created first before using it.

**Comment by dploeger** [comment]
@timdeluxe Yes. You're right. I've modified the workflow a bit to make this more clear.

**Review by timdeluxe — APPROVED** [review]
Thanks! 🎁

**Comment by dploeger** [comment]
@ThomasMinor @timdeluxe Because of a lot of incompatibilities, version unavailabilities etc. this PR now also includes a rewrite of the CCC client in a current Vue version and a changed workflow for installing AWSsudo. :(

I hope, it's still review-able.

**Review by timdeluxe — APPROVED** [review]
Well it is kind of a new software now 😃
But couldn't find bigger issues and i guess you tested it already, so i am fine with it...

**Review by ThomasMinor — APPROVED** [review]
That's a lot for some labels :)

**Pull request merged**
